name: geges_smartbarber
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8

  # START: FIREBASE & CORE
  firebase_core: ^3.4.0       # Inti koneksi ke Firebase
  firebase_auth: ^5.2.0       # Login / Authentication
  cloud_firestore: ^5.3.0     # Database utama Firestore
  provider: ^6.1.2            # Manajemen state
  # END: FIREBASE & CORE
  
  # START: AI/CV COMPONENTS
  google_mlkit_face_detection: ^0.11.0
  image_picker: ^1.1.2
  # END: AI/CV COMPONENTS

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
