import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:geges_smartbarber/firebase_options.dart';
import 'package:geges_smartbarber/services/rating_service.dart';
import 'package:geges_smartbarber/models/app_rating.dart';
import 'package:flutter/foundation.dart';

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  testWidgets('SEEDER: Submit Real Reviews to Firestore via RatingService', (WidgetTester tester) async {
    // 1. Initialize Firebase
    await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
    
    // 2. Setup Auth (Anonymous or Specific)
    final auth = FirebaseAuth.instance;
    User? user = auth.currentUser;
    if (user == null) {
      debugPrint("🔐 Signing in via Email/Password for seeding...");
      try {
        final randomEmail = 'seeder_${DateTime.now().millisecondsSinceEpoch}@test.com';
        final cred = await auth.createUserWithEmailAndPassword(
          email: randomEmail,
          password: 'Password123!',
        );
        user = cred.user;
      } catch (e) {
        debugPrint("⚠️ Create user failed: $e");
        // Try sign in as fallback if somehow collision (rare)
        try {
           final cred = await auth.signInWithEmailAndPassword(email: 'seeder_fallback@test.com', password: 'Password123!');
           user = cred.user;
        } catch (e2) {
           debugPrint("❌ Fatal Auth Error: $e2");
           rethrow;
        }
      }
    }
    debugPrint("👤 Seeding as User: ${user!.uid}");

    // 3. Prepare Data to Seed
    final List<Map<String, dynamic>> reviewsToSeed = [
      {
        'text': 'Pelayanan sangat memuaskan, potongannya rapi dan barbernya ramah banget!',
        'stars': 5.0,
        'shopId': 'geges-shop-1',
        'shopName': 'Geges Barber Slawi',
        'desc': 'Expected: POSITIF (Saved)',
      },
      {
        'text': 'Tempatnya panas, antrian lama, hasil cukurnya tidak rata. Kecewa.',
        'stars': 1.0,
        'shopId': 'febrian-shop-2',
        'shopName': 'Febrian Barbershop',
        'desc': 'Expected: NEGATIF (Saved)',
      },
      {
        'text': 'Lumayan lah, standar aja seperti barbershop biasa.',
        'stars': 3.0,
        'shopId': 'geges-shop-1',
        'shopName': 'Geges Barber Slawi',
        'desc': 'Expected: NETRAL/MIXED (Skipped/Saved depending on model)',
      },
      {
        'text': 'Gokil, hasilnya keren parah! Next bakal langganan di sini.',
        'stars': 5.0,
        'shopId': 'andi-shop-3',
        'shopName': 'Andi Premium Cut',
        'desc': 'Expected: POSITIF (Saved)',
      },
      {
        'text': 'Mahal doang tapi kualitas nol. Gak recommended.',
        'stars': 2.0,
        'shopId': 'febrian-shop-2',
        'shopName': 'Febrian Barbershop',
        'desc': 'Expected: NEGATIF (Saved)',
      },
    ];

    final ratingService = RatingService();
    final firestore = FirebaseFirestore.instance;

    // 4. Execute Seeding
    debugPrint("\n🚀 STARTING SEEDER PROCESS...\n");

    for (var review in reviewsToSeed) {
      final String text = review['text'];
      final double stars = review['stars'];
      final String desc = review['desc'];

      debugPrint("---------------------------------------------------");
      debugPrint("📝 Processing: $desc");
      debugPrint("TEXT: \"$text\"");

      final rating = AppRating(
        id: '', // Generated by Firestore
        userId: user.uid,
        userName: 'Customer Testing',
        userEmail: 'customer@test.com',
        rating: stars,
        feedback: text,
        platform: 'seeder_script',
        createdAt: DateTime.now(),
        barbershopId: review['shopId'],
        barbershopName: review['shopName'],
      );

      try {
        await ratingService.submitRating(rating);
        // Wait a bit to prevent rate limiting or race conditions
        await Future.delayed(const Duration(milliseconds: 500)); 
      } catch (e) {
        debugPrint("❌ Failed to process review: $e");
      }
    }

    debugPrint("\n---------------------------------------------------");
    debugPrint("✅ SEEDER FINISHED.");
    debugPrint("⏳ Verifying Firestore Data...");

    // 5. Verify Data in Firestore
    // We wait a moment for Firestore to index/write
    await Future.delayed(const Duration(seconds: 2));

    final snapshot = await firestore
        .collection('app_ratings')
        .where('platform', isEqualTo: 'seeder_script')
        .get();

    // Sort client-side to avoid Firestore Index requirement
    final docs = snapshot.docs.toList()
      ..sort((a, b) {
        final tA = (a.data()['createdAt'] as Timestamp).toDate();
        final tB = (b.data()['createdAt'] as Timestamp).toDate();
        return tB.compareTo(tA);
      });

    debugPrint("📊 Found ${docs.length} seeded reviews in Firestore:");
    for (var doc in docs.take(10)) {
      final data = doc.data();
      debugPrint("   - [${data['sentiment']?.toUpperCase()}] ${data['feedback']} (Confidence: ${data['sentimentConfidence']})");
    }
    
    expect(docs.length, greaterThanOrEqualTo(1), reason: "At least positive/negative reviews should be saved.");
  });
}
