import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:geges_smartbarber/firebase_options.dart';
import 'package:geges_smartbarber/services/rating_service.dart';
import 'package:geges_smartbarber/models/app_rating.dart';
import 'package:flutter/foundation.dart';

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  testWidgets('SEEDER: Submit Real Reviews to Firestore via RatingService', (WidgetTester tester) async {
    // 1. Initialize Firebase
    await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
    
    // 2. Setup Auth (Anonymous or Specific)
    final auth = FirebaseAuth.instance;
    User? user = auth.currentUser;
    if (user == null) {
      debugPrint("🔐 Signing in anonymously for seeding...");
      final cred = await auth.signInAnonymously();
      user = cred.user;
    }
    debugPrint("👤 Seeding as User: ${user!.uid}");

    // 3. Prepare Data to Seed
    final List<Map<String, dynamic>> reviewsToSeed = [
      {
        'text': 'Pelayanan sangat memuaskan, potongannya rapi dan barbernya ramah banget!',
        'stars': 5.0,
        'shopId': 'geges-shop-1',
        'shopName': 'Geges Barber Slawi',
        'desc': 'Expected: POSITIF (Saved)',
      },
      {
        'text': 'Tempatnya panas, antrian lama, hasil cukurnya tidak rata. Kecewa.',
        'stars': 1.0,
        'shopId': 'febrian-shop-2',
        'shopName': 'Febrian Barbershop',
        'desc': 'Expected: NEGATIF (Saved)',
      },
      {
        'text': 'Lumayan lah, standar aja seperti barbershop biasa.',
        'stars': 3.0,
        'shopId': 'geges-shop-1',
        'shopName': 'Geges Barber Slawi',
        'desc': 'Expected: NETRAL/MIXED (Skipped/Saved depending on model)',
      },
      {
        'text': 'Gokil, hasilnya keren parah! Next bakal langganan di sini.',
        'stars': 5.0,
        'shopId': 'andi-shop-3',
        'shopName': 'Andi Premium Cut',
        'desc': 'Expected: POSITIF (Saved)',
      },
      {
        'text': 'Mahal doang tapi kualitas nol. Gak recommended.',
        'stars': 2.0,
        'shopId': 'febrian-shop-2',
        'shopName': 'Febrian Barbershop',
        'desc': 'Expected: NEGATIF (Saved)',
      },
    ];

    final ratingService = RatingService();
    final firestore = FirebaseFirestore.instance;

    // 4. Execute Seeding
    debugPrint("\n🚀 STARTING SEEDER PROCESS...\n");

    for (var review in reviewsToSeed) {
      final String text = review['text'];
      final double stars = review['stars'];
      final String desc = review['desc'];

      debugPrint("---------------------------------------------------");
      debugPrint("📝 Processing: $desc");
      debugPrint("TEXT: \"$text\"");

      final rating = AppRating(
        id: '', // Generated by Firestore
        userId: user.uid,
        userName: 'Customer Testing',
        userEmail: 'customer@test.com',
        rating: stars,
        feedback: text,
        platform: 'seeder_script',
        createdAt: DateTime.now(),
        barbershopId: review['shopId'],
        barbershopName: review['shopName'],
      );

      try {
        await ratingService.submitRating(rating);
        // Wait a bit to prevent rate limiting or race conditions
        await Future.delayed(const Duration(milliseconds: 500)); 
      } catch (e) {
        debugPrint("❌ Failed to process review: $e");
      }
    }

    debugPrint("\n---------------------------------------------------");
    debugPrint("✅ SEEDER FINISHED.");
    debugPrint("⏳ Verifying Firestore Data...");

    // 5. Verify Data in Firestore
    // We wait a moment for Firestore to index/write
    await Future.delayed(const Duration(seconds: 2));

    final snapshot = await firestore
        .collection('app_ratings')
        .where('platform', isEqualTo: 'seeder_script')
        .orderBy('createdAt', descending: true)
        .limit(10)
        .get();

    debugPrint("📊 Found ${snapshot.docs.length} seeded reviews in Firestore:");
    for (var doc in snapshot.docs) {
      final data = doc.data();
      debugPrint("   - [${data['sentiment']?.toUpperCase()}] ${data['feedback']} (Confidence: ${data['sentimentConfidence']})");
    }
    
    expect(snapshot.docs.length, greaterThanOrEqualTo(1), reason: "At least positive/negative reviews should be saved.");
  });
}
