// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB2mkhbMiuKnvybfU-fIRhvWXnADEZa5o',
    appId: '1:51527807075:web:4943c3694db47a720a4856',
    messagingSenderId: '51527807075',
    projectId: 'geges-smartbarber-project',
    authDomain: 'geges-smartbarber-project.firebaseapp.com',
    storageBucket: 'geges-smartbarber-project.firebasestorage.app',
    measurementId: 'G-PGDQQQMVF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtqlNucmw3zjqL1RE-uz6_UcD4Kv1hPoo',
    appId: '1:51527807075:android:4ac445a0dfdad2420a4856',
    messagingSenderId: '51527807075',
    projectId: 'geges-smartbarber-project',
    storageBucket: 'geges-smartbarber-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjfVfGjF_YbLw9Rq6D8idRVZsTS16RqxY',
    appId: '1:51527807075:ios:6443cdd21fe9fee90a4856',
    messagingSenderId: '51527807075',
    projectId: 'geges-smartbarber-project',
    storageBucket: 'geges-smartbarber-project.firebasestorage.app',
    iosBundleId: 'com.example.gegesSmartbarber',
  );
}
