// Mocks generated by Mockito 5.4.6 from annotations
// in geges_smartbarber/test/widget/booking/appointment_notes_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:flutter/material.dart' as _i13;
import 'package:geges_smartbarber/models/barberman.dart' as _i6;
import 'package:geges_smartbarber/models/barbershop.dart' as _i5;
import 'package:geges_smartbarber/models/promo_banner.dart' as _i9;
import 'package:geges_smartbarber/models/queue.dart' as _i10;
import 'package:geges_smartbarber/models/service.dart' as _i7;
import 'package:geges_smartbarber/models/user_data.dart' as _i11;
import 'package:geges_smartbarber/services/barbershop_service.dart' as _i3;
import 'package:geges_smartbarber/services/queue_service.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDocumentReference_0<T extends Object?> extends _i1.SmartFake
    implements _i2.DocumentReference<T> {
  _FakeDocumentReference_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQuerySnapshot_1<T extends Object?> extends _i1.SmartFake
    implements _i2.QuerySnapshot<T> {
  _FakeQuerySnapshot_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BarbershopService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBarbershopService extends _i1.Mock implements _i3.BarbershopService {
  @override
  _i4.Future<List<_i5.Barbershop>> getAllBarbershops(
          {bool? forceRefresh = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllBarbershops,
          [],
          {#forceRefresh: forceRefresh},
        ),
        returnValue: _i4.Future<List<_i5.Barbershop>>.value(<_i5.Barbershop>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.Barbershop>>.value(<_i5.Barbershop>[]),
      ) as _i4.Future<List<_i5.Barbershop>>);

  @override
  _i4.Stream<List<_i5.Barbershop>> streamAllBarbershops() =>
      (super.noSuchMethod(
        Invocation.method(
          #streamAllBarbershops,
          [],
        ),
        returnValue: _i4.Stream<List<_i5.Barbershop>>.empty(),
        returnValueForMissingStub: _i4.Stream<List<_i5.Barbershop>>.empty(),
      ) as _i4.Stream<List<_i5.Barbershop>>);

  @override
  _i4.Stream<_i5.Barbershop?> streamBarbershopById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamBarbershopById,
          [id],
        ),
        returnValue: _i4.Stream<_i5.Barbershop?>.empty(),
        returnValueForMissingStub: _i4.Stream<_i5.Barbershop?>.empty(),
      ) as _i4.Stream<_i5.Barbershop?>);

  @override
  _i4.Future<void> setBarbershopActiveStatus(
    String? id,
    bool? isActive,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBarbershopActiveStatus,
          [
            id,
            isActive,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i5.Barbershop?> getBarbershopById(String? barbershopId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBarbershopById,
          [barbershopId],
        ),
        returnValue: _i4.Future<_i5.Barbershop?>.value(),
        returnValueForMissingStub: _i4.Future<_i5.Barbershop?>.value(),
      ) as _i4.Future<_i5.Barbershop?>);

  @override
  _i4.Future<void> updateSpecialOrderFee(
    String? barbershopId,
    int? fee,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSpecialOrderFee,
          [
            barbershopId,
            fee,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateShopStatus(
    String? id,
    bool? isOpen,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShopStatus,
          [
            id,
            isOpen,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.Barberman>> getBarbermenByShop(String? barbershopId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBarbermenByShop,
          [barbershopId],
        ),
        returnValue: _i4.Future<List<_i6.Barberman>>.value(<_i6.Barberman>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i6.Barberman>>.value(<_i6.Barberman>[]),
      ) as _i4.Future<List<_i6.Barberman>>);

  @override
  _i4.Future<_i6.Barberman?> getBarbermanById(String? barbermanId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBarbermanById,
          [barbermanId],
        ),
        returnValue: _i4.Future<_i6.Barberman?>.value(),
        returnValueForMissingStub: _i4.Future<_i6.Barberman?>.value(),
      ) as _i4.Future<_i6.Barberman?>);

  @override
  _i4.Future<String> saveService(_i7.Service? service) => (super.noSuchMethod(
        Invocation.method(
          #saveService,
          [service],
        ),
        returnValue: _i4.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #saveService,
            [service],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #saveService,
            [service],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> deleteService(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteService,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateBarbershopSettings(
    String? id,
    Map<String, dynamic>? settings,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBarbershopSettings,
          [
            id,
            settings,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addServiceToBarbershop(
    String? shopId,
    String? serviceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addServiceToBarbershop,
          [
            shopId,
            serviceId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> removeServiceFromBarbershop(
    String? shopId,
    String? serviceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeServiceFromBarbershop,
          [
            shopId,
            serviceId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addGalleryImage(
    String? barbershopId,
    String? base64Image,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addGalleryImage,
          [
            barbershopId,
            base64Image,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> removeGalleryImage(
    String? barbershopId,
    String? base64Image,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeGalleryImage,
          [
            barbershopId,
            base64Image,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveBarberman(_i6.Barberman? barber) => (super.noSuchMethod(
        Invocation.method(
          #saveBarberman,
          [barber],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteBarberman(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteBarberman,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateBarbermanLeave(
    String? id, {
    required bool? onLeave,
    List<String>? specificOffDays,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBarbermanLeave,
          [id],
          {
            #onLeave: onLeave,
            #specificOffDays: specificOffDays,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i7.Service>> getAllServices() => (super.noSuchMethod(
        Invocation.method(
          #getAllServices,
          [],
        ),
        returnValue: _i4.Future<List<_i7.Service>>.value(<_i7.Service>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i7.Service>>.value(<_i7.Service>[]),
      ) as _i4.Future<List<_i7.Service>>);

  @override
  _i4.Future<List<_i7.Service>> getServicesByIds(List<String>? ids) =>
      (super.noSuchMethod(
        Invocation.method(
          #getServicesByIds,
          [ids],
        ),
        returnValue: _i4.Future<List<_i7.Service>>.value(<_i7.Service>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i7.Service>>.value(<_i7.Service>[]),
      ) as _i4.Future<List<_i7.Service>>);

  @override
  _i4.Stream<List<_i9.PromoBanner>> getPromoBanners() => (super.noSuchMethod(
        Invocation.method(
          #getPromoBanners,
          [],
        ),
        returnValue: _i4.Stream<List<_i9.PromoBanner>>.empty(),
        returnValueForMissingStub: _i4.Stream<List<_i9.PromoBanner>>.empty(),
      ) as _i4.Stream<List<_i9.PromoBanner>>);

  @override
  _i4.Stream<List<_i10.Queue>> streamActiveQueuesByShop(String? barbershopId) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamActiveQueuesByShop,
          [barbershopId],
        ),
        returnValue: _i4.Stream<List<_i10.Queue>>.empty(),
        returnValueForMissingStub: _i4.Stream<List<_i10.Queue>>.empty(),
      ) as _i4.Stream<List<_i10.Queue>>);

  @override
  _i4.Stream<List<_i10.Queue>> streamWaitingQueues(String? barbershopId) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamWaitingQueues,
          [barbershopId],
        ),
        returnValue: _i4.Stream<List<_i10.Queue>>.empty(),
        returnValueForMissingStub: _i4.Stream<List<_i10.Queue>>.empty(),
      ) as _i4.Stream<List<_i10.Queue>>);

  @override
  _i4.Future<void> updateQueueStatus(
    String? queueId,
    String? newStatus, {
    Map<String, dynamic>? extra,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateQueueStatus,
          [
            queueId,
            newStatus,
          ],
          {#extra: extra},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> cancelQueue(
    String? queueId, {
    String? reason = 'Cancelled by system/admin',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelQueue,
          [queueId],
          {#reason: reason},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> startService(String? queueId) => (super.noSuchMethod(
        Invocation.method(
          #startService,
          [queueId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> finishService(String? queueId) => (super.noSuchMethod(
        Invocation.method(
          #finishService,
          [queueId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<_i11.UserData?> getUserDataStream(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserDataStream,
          [userId],
        ),
        returnValue: _i4.Stream<_i11.UserData?>.empty(),
        returnValueForMissingStub: _i4.Stream<_i11.UserData?>.empty(),
      ) as _i4.Stream<_i11.UserData?>);

  @override
  _i4.Future<_i2.DocumentReference<Map<String, dynamic>>> createQueue(
          Map<String, dynamic>? queueData) =>
      (super.noSuchMethod(
        Invocation.method(
          #createQueue,
          [queueData],
        ),
        returnValue:
            _i4.Future<_i2.DocumentReference<Map<String, dynamic>>>.value(
                _FakeDocumentReference_0<Map<String, dynamic>>(
          this,
          Invocation.method(
            #createQueue,
            [queueData],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.DocumentReference<Map<String, dynamic>>>.value(
                _FakeDocumentReference_0<Map<String, dynamic>>(
          this,
          Invocation.method(
            #createQueue,
            [queueData],
          ),
        )),
      ) as _i4.Future<_i2.DocumentReference<Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.QuerySnapshot<Map<String, dynamic>>> getQueuesByOrderId(
          String? orderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQueuesByOrderId,
          [orderId],
        ),
        returnValue: _i4.Future<_i2.QuerySnapshot<Map<String, dynamic>>>.value(
            _FakeQuerySnapshot_1<Map<String, dynamic>>(
          this,
          Invocation.method(
            #getQueuesByOrderId,
            [orderId],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.QuerySnapshot<Map<String, dynamic>>>.value(
                _FakeQuerySnapshot_1<Map<String, dynamic>>(
          this,
          Invocation.method(
            #getQueuesByOrderId,
            [orderId],
          ),
        )),
      ) as _i4.Future<_i2.QuerySnapshot<Map<String, dynamic>>>);

  @override
  _i4.Future<_i6.Barberman?> pickDefaultBarber(
    String? barbershopId,
    DateTime? bookingTime, {
    int? durationMinutes,
    int? lookaheadMinutes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickDefaultBarber,
          [
            barbershopId,
            bookingTime,
          ],
          {
            #durationMinutes: durationMinutes,
            #lookaheadMinutes: lookaheadMinutes,
          },
        ),
        returnValue: _i4.Future<_i6.Barberman?>.value(),
        returnValueForMissingStub: _i4.Future<_i6.Barberman?>.value(),
      ) as _i4.Future<_i6.Barberman?>);

  @override
  _i4.Future<List<_i5.Barbershop>> searchBarbershops(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchBarbershops,
          [query],
        ),
        returnValue: _i4.Future<List<_i5.Barbershop>>.value(<_i5.Barbershop>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.Barbershop>>.value(<_i5.Barbershop>[]),
      ) as _i4.Future<List<_i5.Barbershop>>);

  @override
  _i4.Future<void> toggleFavorite(
    String? userId,
    String? barbershopId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleFavorite,
          [
            userId,
            barbershopId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> isFavorite(
    String? userId,
    String? barbershopId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isFavorite,
          [
            userId,
            barbershopId,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Stream<List<String>> streamFavoriteIds(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamFavoriteIds,
          [userId],
        ),
        returnValue: _i4.Stream<List<String>>.empty(),
        returnValueForMissingStub: _i4.Stream<List<String>>.empty(),
      ) as _i4.Stream<List<String>>);

  @override
  _i4.Future<List<_i5.Barbershop>> getFavoriteBarbershops(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavoriteBarbershops,
          [userId],
        ),
        returnValue: _i4.Future<List<_i5.Barbershop>>.value(<_i5.Barbershop>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.Barbershop>>.value(<_i5.Barbershop>[]),
      ) as _i4.Future<List<_i5.Barbershop>>);
}

/// A class which mocks [QueueService].
///
/// See the documentation for Mockito's code generation for more information.
class MockQueueService extends _i1.Mock implements _i12.QueueService {
  @override
  _i4.Stream<int> streamUnreadNotificationCount(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamUnreadNotificationCount,
          [userId],
        ),
        returnValue: _i4.Stream<int>.empty(),
        returnValueForMissingStub: _i4.Stream<int>.empty(),
      ) as _i4.Stream<int>);

  @override
  _i4.Future<String?> getFairAvailableBarberman({
    required String? barbershopId,
    required DateTime? bookingTime,
    required List<String>? serviceIds,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFairAvailableBarberman,
          [],
          {
            #barbershopId: barbershopId,
            #bookingTime: bookingTime,
            #serviceIds: serviceIds,
          },
        ),
        returnValue: _i4.Future<String?>.value(),
        returnValueForMissingStub: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Stream<List<_i10.Queue>> streamQueuesForBarbershop(
    String? barbershopId, {
    List<String>? statusFilter,
    String? barbermanIdFilter,
    DateTime? startDate,
    DateTime? endDate,
    int? limit = 100,
    _i2.DocumentSnapshot<Object?>? startAfter,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamQueuesForBarbershop,
          [barbershopId],
          {
            #statusFilter: statusFilter,
            #barbermanIdFilter: barbermanIdFilter,
            #startDate: startDate,
            #endDate: endDate,
            #limit: limit,
            #startAfter: startAfter,
          },
        ),
        returnValue: _i4.Stream<List<_i10.Queue>>.empty(),
        returnValueForMissingStub: _i4.Stream<List<_i10.Queue>>.empty(),
      ) as _i4.Stream<List<_i10.Queue>>);

  @override
  _i4.Stream<List<_i10.Queue>> streamQueuesForCustomer(
    String? customerId, {
    List<String>? statusFilter,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamQueuesForCustomer,
          [customerId],
          {#statusFilter: statusFilter},
        ),
        returnValue: _i4.Stream<List<_i10.Queue>>.empty(),
        returnValueForMissingStub: _i4.Stream<List<_i10.Queue>>.empty(),
      ) as _i4.Stream<List<_i10.Queue>>);

  @override
  _i4.Stream<_i10.Queue?> streamQueueById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #streamQueueById,
          [id],
        ),
        returnValue: _i4.Stream<_i10.Queue?>.empty(),
        returnValueForMissingStub: _i4.Stream<_i10.Queue?>.empty(),
      ) as _i4.Stream<_i10.Queue?>);

  @override
  _i4.Future<_i10.Queue?> getQueueById(String? queueId) => (super.noSuchMethod(
        Invocation.method(
          #getQueueById,
          [queueId],
        ),
        returnValue: _i4.Future<_i10.Queue?>.value(),
        returnValueForMissingStub: _i4.Future<_i10.Queue?>.value(),
      ) as _i4.Future<_i10.Queue?>);

  @override
  _i4.Stream<List<_i10.Queue>> streamAllQueues({List<String>? statusFilter}) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamAllQueues,
          [],
          {#statusFilter: statusFilter},
        ),
        returnValue: _i4.Stream<List<_i10.Queue>>.empty(),
        returnValueForMissingStub: _i4.Stream<List<_i10.Queue>>.empty(),
      ) as _i4.Stream<List<_i10.Queue>>);

  @override
  _i4.Future<void> adminRejectCancellation(String? queueId) =>
      (super.noSuchMethod(
        Invocation.method(
          #adminRejectCancellation,
          [queueId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<int> cancelExpiredWaitingQueuesForCustomer(String? customerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelExpiredWaitingQueuesForCustomer,
          [customerId],
        ),
        returnValue: _i4.Future<int>.value(0),
        returnValueForMissingStub: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<List<_i13.DateTimeRange<DateTime>>> getBarberBusyTimeRanges(
    String? barbermanId,
    DateTime? date,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBarberBusyTimeRanges,
          [
            barbermanId,
            date,
          ],
        ),
        returnValue: _i4.Future<List<_i13.DateTimeRange<DateTime>>>.value(
            <_i13.DateTimeRange<DateTime>>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i13.DateTimeRange<DateTime>>>.value(
                <_i13.DateTimeRange<DateTime>>[]),
      ) as _i4.Future<List<_i13.DateTimeRange<DateTime>>>);

  @override
  _i4.Future<List<_i13.DateTimeRange<DateTime>>> getShopBusySlots({
    required String? barbershopId,
    required DateTime? date,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getShopBusySlots,
          [],
          {
            #barbershopId: barbershopId,
            #date: date,
          },
        ),
        returnValue: _i4.Future<List<_i13.DateTimeRange<DateTime>>>.value(
            <_i13.DateTimeRange<DateTime>>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i13.DateTimeRange<DateTime>>>.value(
                <_i13.DateTimeRange<DateTime>>[]),
      ) as _i4.Future<List<_i13.DateTimeRange<DateTime>>>);

  @override
  _i4.Future<int> cancelExpiredBookings(String? barbershopId) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelExpiredBookings,
          [barbershopId],
        ),
        returnValue: _i4.Future<int>.value(0),
        returnValueForMissingStub: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<void> startService(String? queueId) => (super.noSuchMethod(
        Invocation.method(
          #startService,
          [queueId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> finishService(
    String? queueId, [
    _i2.Timestamp? startTime,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #finishService,
          [
            queueId,
            startTime,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> cancelQueue(
    String? queueId, {
    String? reason = 'Cancellation',
    String? cancelledBy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelQueue,
          [queueId],
          {
            #reason: reason,
            #cancelledBy: cancelledBy,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteQueue(String? queueId) => (super.noSuchMethod(
        Invocation.method(
          #deleteQueue,
          [queueId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> adminConfirmRequest(
    String? queueId, {
    String? adminUid,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #adminConfirmRequest,
          [queueId],
          {#adminUid: adminUid},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> adminRejectRequest(
    String? queueId, {
    String? rejectionReason,
    String? adminUid,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #adminRejectRequest,
          [queueId],
          {
            #rejectionReason: rejectionReason,
            #adminUid: adminUid,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> adminConfirmPayment(
    String? queueId, {
    String? adminUid,
    String? adminNotes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #adminConfirmPayment,
          [queueId],
          {
            #adminUid: adminUid,
            #adminNotes: adminNotes,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> adminRejectPayment(
    String? queueId, {
    String? reason,
    String? adminUid,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #adminRejectPayment,
          [queueId],
          {
            #reason: reason,
            #adminUid: adminUid,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> adminProcessRefund(
    String? queueId, {
    required String? refundProofBase64,
    String? adminUid,
    String? adminNotes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #adminProcessRefund,
          [queueId],
          {
            #refundProofBase64: refundProofBase64,
            #adminUid: adminUid,
            #adminNotes: adminNotes,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> adminRefundBooking(
    String? queueId, {
    String? reason,
    String? adminUid,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #adminRefundBooking,
          [queueId],
          {
            #reason: reason,
            #adminUid: adminUid,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.DocumentReference<Map<String, dynamic>>> createQueue(
          Map<String, dynamic>? queueData) =>
      (super.noSuchMethod(
        Invocation.method(
          #createQueue,
          [queueData],
        ),
        returnValue:
            _i4.Future<_i2.DocumentReference<Map<String, dynamic>>>.value(
                _FakeDocumentReference_0<Map<String, dynamic>>(
          this,
          Invocation.method(
            #createQueue,
            [queueData],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.DocumentReference<Map<String, dynamic>>>.value(
                _FakeDocumentReference_0<Map<String, dynamic>>(
          this,
          Invocation.method(
            #createQueue,
            [queueData],
          ),
        )),
      ) as _i4.Future<_i2.DocumentReference<Map<String, dynamic>>>);

  @override
  _i4.Future<bool> isSlotAvailable({
    required String? barbershopId,
    required String? barbermanId,
    required DateTime? bookingTime,
    required List<String>? serviceIds,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #isSlotAvailable,
          [],
          {
            #barbershopId: barbershopId,
            #barbermanId: barbermanId,
            #bookingTime: bookingTime,
            #serviceIds: serviceIds,
          },
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<int> getPaymentWindowForBarbershop(String? barbershopId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPaymentWindowForBarbershop,
          [barbershopId],
        ),
        returnValue: _i4.Future<int>.value(0),
        returnValueForMissingStub: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<_i10.Queue?> resolveQueueForCustomerByIdOrOrder(
    String? idOrOrderId,
    String? customerId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #resolveQueueForCustomerByIdOrOrder,
          [
            idOrOrderId,
            customerId,
          ],
        ),
        returnValue: _i4.Future<_i10.Queue?>.value(),
        returnValueForMissingStub: _i4.Future<_i10.Queue?>.value(),
      ) as _i4.Future<_i10.Queue?>);

  @override
  _i4.Future<void> submitPaymentProofForQueue({
    required String? queueId,
    required String? userId,
    required String? base64Proof,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitPaymentProofForQueue,
          [],
          {
            #queueId: queueId,
            #userId: userId,
            #base64Proof: base64Proof,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> customerRequestCancellation(
    String? queueId, {
    required String? reason,
    String? customerId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customerRequestCancellation,
          [queueId],
          {
            #reason: reason,
            #customerId: customerId,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> withdrawCancellationRequest(String? queueId) =>
      (super.noSuchMethod(
        Invocation.method(
          #withdrawCancellationRequest,
          [queueId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<int> cancelExpiredAwaitingPaymentQueuesForCustomer(
          String? customerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelExpiredAwaitingPaymentQueuesForCustomer,
          [customerId],
        ),
        returnValue: _i4.Future<int>.value(0),
        returnValueForMissingStub: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);
}
